servers:
  hosts:
    "{{cookiecutter.domain}}":
      app: {{cookiecutter.project_slug}}
      domain: {{cookiecutter.domain}}
      app_image: {{cookiecutter.docker_registry}}/{{cookiecutter.docker_username}}/{{cookiecutter.project_slug}}
      db_password: {{cookiecutter.db_password}}
      access_token: {{cookiecutter.access_token}}
      app_extra_ports: []

  vars:
      docker_registry: {{cookiecutter.docker_registry}}
      docker_username: {{cookiecutter.docker_username}}
      docker_password: {{cookiecutter.docker_password}}
